### ISSUE TITLE
Tampermonkeyを使わない方法（iOS）について

### ISSUE THREAD

**Issue by Kei-Toba** [hi2ma-bu4/X_impression_hide#1]
UserscriptsというiOS Safari向けの拡張機能があるのですが、そのアプリでも使えますか？
そのまま入れてみましたが、うまく機能していない気がします。
https://apps.apple.com/jp/app/userscripts/id1463298887

**Comment by hi2ma-bu4** [comment]
すみません。
現在、Apple系の環境が無く検証が出来ない状況であり、修正が難しいかもしれません。
ご時間あれば、『どの様に動かない』などの状況を詳しく教えて頂けると幸いです。

**Comment by Kei-Toba** [comment]
今のところだと全く機能していないと思います。この拡張機能はMac版とiOS版があるのですが、iOS版はおそらくバージョンが遅れているのでその影響を少し疑っています。
私の設定ミスというのも大いにありえるのですが、このアプリでのメタデータ等の扱いがTampermonkeyの仕様とは少し異なっており、そのことが原因になっている可能性があるかもしれない…という稀なケースもちょっとだけ考えています。

**Comment by hi2ma-bu4** [comment]
Userscriptsについて調べてみたのですが、以下の関数が定義されていないように感じました。
多分Tampermonkeyの独自実装ですね。
https://github.com/hi2ma-bu4/X_impression_hide/blob/66ee7e9955519eb18bbb88b41a6602d8f7c84789/script.user.js#L26-L30

どうにかしてSafariのTampermonkeyとUserscriptsを判定する機構が作れれば解決すると思います。

> 追記
> `GM_setValue`、`GM_getValue`、`GM_deleteValue`が再現出来ない(設定データを保存出来ない)かもしれません。
>
>> 再追記
>> [公式リファレンス](https://github.com/quoid/userscripts/)を確認した所、`GM_setValue`等は`GM.setValue`などに変更すれば動作する様になるかもしれません。
>> 次のバージョンで修正します。
>> 動作しなかった場合は再度ご報告下さい。

**Comment by hi2ma-bu4** [comment]
取り敢えず
https://github.com/hi2ma-bu4/X_impression_hide/blob/65c4c7788b4a7edb3b8d6baa52c60010f985341f/script.user.js#L26-L30
の部分を変更してみました。
動作確認お願いします。

(`GM.registerMenuCommand`を対処していないので設定画面が表示出来ないかもしれませんが動作は一応するはずです)

> 追記(v1.13.2)
> `GM.registerMenuCommand`が存在しない場合にスキップするように変更しました。

**Comment by Kei-Toba** [comment]
![IMG_0824](https://github.com/hi2ma-bu4/X_impression_hide/assets/60617580/238fb1bc-e882-4f06-ba2f-54339048f125)
ありがとうございます。動作確認できました。

**Comment by hi2ma-bu4** [comment]
この画像の情報から設定メニューも開けた感じですか？
開けた場合はこのissueはcloseします。

**Comment by Kei-Toba** [comment]
設定メニューはおそらく開けないかと思います（どこを押したらメニューが出てくるのかわからないです）。
認証アカウントがブロックされているのはVerifyBlockをtrueに書き換えたからですね。

**Comment by hi2ma-bu4** [comment]
直接設定を編集した感じですか...
わかりました。設定もどうにか頑張ってみます。

**Comment by Kei-Toba** [comment]
余談ですがTwitterのPWA（ホーム画面に追加）だとどうやら動作しないようです（完全にAppleのせい）

**Comment by hi2ma-bu4** [comment]
そうですねそれはappleが悪いです。
(私には多分どうしようもない)

**Comment by hi2ma-bu4** [comment]
~~少々意見を頂きたいのですが、もしメニューを開くボタンを直接ページに設置するとした場合、画面の右上、右下、左上、左下、その他、のどれが良いですか？~~
> 追記
> 既存のメニューにめり込ませる方式にしました。

**Comment by Kei-Toba** [comment]
返信が遅れてしまいましたが、 iPadだと左端にメニューがあり、iPhoneだとおそらく右下にツイートボタンがあるはずなので（未確認）、右上はどうかなと考えていました。
何らかの事情で直接設置せざるを得ない時の参考になれば幸いです。

**Comment by hi2ma-bu4** [comment]
v1.13.3
仮で右上にボタンを設置してみました。

(twitterUI変更があったようで、連投検知機能が壊れていたので停止しています。)

**Comment by Kei-Toba** [comment]
![IMG_0828](https://github.com/hi2ma-bu4/X_impression_hide/assets/60617580/c0289c03-ae49-4223-966b-81df61e7b39e)
![IMG_0827](https://github.com/hi2ma-bu4/X_impression_hide/assets/60617580/78428d62-9d97-42a8-979a-a187ba21aaf5)
ありがとうございます。
iPadからの写真ですがこのようにしっかり動きました。項目にチェックマークを入れてページ更新するときちんと有効になるのも確認できました。disp:menuが小さいのでもう少し大きくしていただけると嬉しいです。

**Comment by hi2ma-bu4** [comment]
了解しました。明日、2.5倍前後のサイズで調整してみます。

**Comment by hi2ma-bu4** [comment]
v1.13.7
ボタンサイズを10em x 2em にしたのでおおよそ2倍のサイズになったと思います。
私の環境Android(kiwi)ではおおよそこれで丁度良いサイズになりましたので、スマホ環境のサイズは10x2に決定しました。
タブレットは検証出来ていない事をご了承ください。

細かいCSS修正は`設定メニュー>高度な設定>ページ適用css設定`の一番下の`#X_impression_hide_menu_openBtn`の`{}`の中の`width`と`height`より変更をお願いします。
適切なサイズ等が見つかりましたら教えて頂けますと場合によっては他環境でも共通化出来るかもしれません。

※現在の仕様の関係上一度変更された項目(全ての設定において)の設定内容はアップデートで更新されません。
アップデートで表示等が可笑しくなりましたら、[GithubのREADME.mdの手順](https://github.com/hi2ma-bu4/X_impression_hide?tab=readme-ov-file#%E8%A8%AD%E5%AE%9A%E3%83%9F%E3%82%B9%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E3%81%AB%E3%82%88%E3%82%8B%E8%A8%AD%E5%AE%9A%E6%9B%B4%E6%96%B0%E3%81%9A%E3%82%8C%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88)でcss設定をリセットするか、
`設定メニュー>高度な設定>設定のリセット`を実行して下さい。
この仕様(問題点)に関しては雑に作った私が悪いので改善案等あれば別のissueを立てて下さい。


> 追記
>> GithubのREADME.mdの手順で
>
> ストレージの中を確認出来ない可能性を忘れてました。
> ここは読み飛ばして貰って構いません。

**Comment by Kei-Toba** [comment]
ありがとうございます。前バージョンよりもかなり押しやすくなりました。
10インチのタブレットだと現バージョンの2倍くらい大きさが良いかもしれません。
先日からの対応がとてもスピーディーで助かりました。愛用させていただきます。
改めてありがとうございました。

**Comment by hi2ma-bu4** [comment]
ありがとうございます。

次のバージョンアップでタブレットサイズは20x4に設定しておきます。

また、機能要望やバグ等ありましたら気軽にissueしてください。
解決したのでこのissueはcloseとします。
